import fs from 'node:fs/promises';import path from 'node:path';import {build} from 'esbuild';import crypto from 'node:crypto';
const hasLLM=!!(await fs.stat('models/rn-qwen/ndarray-cache.json').catch(()=>null));
if(hasLLM){const cache=JSON.parse(await fs.readFile('models/rn-qwen/ndarray-cache.json'));for(const name of ['model.wasm','mlc-chat-config.json','tokenizer.json',...cache.records.map(r=>r.dataPath)])await fs.access('models/rn-qwen/'+name);}
await fs.rm('dist',{recursive:true,force:true});await fs.mkdir('dist',{recursive:true});
await build({define:{__RN_LLM_AVAILABLE__:JSON.stringify(hasLLM),__RN_EMULATORS__:JSON.stringify(process.env.RN_EMULATORS==='1')},entryPoints:['src/App.js','src/engine/llm.worker.js'],outdir:'dist',entryNames:'[name]',chunkNames:'chunks/[name]-[hash]',bundle:true,splitting:true,format:'esm',minify:true,target:'es2022',metafile:true,logLevel:'info'});
// Public web config only; offline modes do not need it.
const firebaseConfig=process.env.RN_FIREBASE_CONFIG||await fs.readFile('firebase-config.json','utf8').catch(()=>null);
if(firebaseConfig)await fs.writeFile('dist/firebase-config.json',JSON.stringify(JSON.parse(firebaseConfig)));
await fs.copyFile('src/style.css','dist/style.css');await fs.copyFile('src/upgrade.css','dist/upgrade.css');
for(const name of ['tutorial','logos'])await fs.cp(name,'dist/'+name,{recursive:true});
await fs.copyFile('favicon.svg','dist/favicon.svg');
await fs.writeFile('dist/index.html',`<!doctype html><html lang="it"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#142a43"><meta name="description" content="Guess the Radionuclide: 59 cards, scientific deduction, Italian English French."><title>Indovina il Radionuclide · Michele Colucci</title><link rel="icon" href="./favicon.svg"><link rel="manifest" href="./manifest.webmanifest"><link rel="stylesheet" href="./style.css"><link rel="stylesheet" href="./upgrade.css"></head><body><div id="root"></div><noscript>Abilita JavaScript · Enable JavaScript · Activez JavaScript.</noscript><script type="module" src="./App.js"></script></body></html>`);
await fs.writeFile('dist/manifest.webmanifest',JSON.stringify({name:'Guess the Radionuclide',short_name:'Radionuclide',start_url:'./',scope:'./',display:'standalone',background_color:'#ffffff',theme_color:'#142a43',icons:[{src:'./favicon.svg',sizes:'any',type:'image/svg+xml',purpose:'any'}]}));
async function files(dir){let out=[];for(const d of await fs.readdir(dir,{withFileTypes:true}))d.isDirectory()?out.push(...await files(path.join(dir,d.name))):out.push(path.join(dir,d.name));return out;}
const list=(await files('dist')).map(f=>'./'+path.relative('dist',f).replaceAll('\\','/'));let hash=crypto.createHash('sha256');for(const f of await files('dist'))hash.update(await fs.readFile(f));const version='rn-v3-'+hash.digest('hex').slice(0,12);
await fs.writeFile('dist/sw.js',`const CACHE=${JSON.stringify(version)},ASSETS=${JSON.stringify(list)};self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS))));self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('rn-v3-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));self.addEventListener('fetch',e=>{if(e.request.method!=='GET'||new URL(e.request.url).origin!==location.origin)return;e.respondWith(caches.match(e.request).then(hit=>hit||fetch(e.request)));});`);
if(hasLLM)await fs.cp('models/rn-qwen','dist/models/rn-qwen/resolve/main',{recursive:true});
await fs.writeFile('dist/.nojekyll','');console.log('Static site built, relative paths and offline cache:',version);
