import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Atom, BookOpen, Globe2, Info, Play, RotateCcw, Search, Sparkles, X } from 'lucide-react';
import './style.css';

const DOI = 'https://doi.org/10.15161/oar.it/77027';

const TEXT = {
  it: { title:'Indovina il Radionuclide', subtitle:'Un gioco radioattivo per i fisici del futuro!', play:'Gioca', atlas:'Atlante', about:'Crediti e fonti', setup:'Configura partita', mode:'Modalità', soloEasy:'Singolo · didattico', soloHard:'Singolo · sfida', local:'Due giocatori · un dispositivo', level:'Livello', explorer:'Esploratore', curious:'Curioso', scientist:'Scienziato', expert:'Esperto', assistance:'Eliminazione', assisted:'Automatica', manual:'Manuale', deck:'Mazzo', full:'Tutte', start:'Inizia', pickSolo:'Scegli la tua carta segreta', pick1:'Giocatore 1, scegli la carta segreta', pick2:'Passa il dispositivo. Giocatore 2, scegli la carta segreta', hide:'Non mostrare la carta all’avversario.', turn:'Turno', player:'Giocatore', computer:'Computer', secret:'La tua carta', ask:'Formula una domanda SÌ/NO', placeholder:'Es. Posso trovarlo in un’insalata coltivata a Fukushima?', submit:'Fai la domanda', guess:'Tenta di indovinare', quick:'Domande suggerite', candidates:'carte possibili', yes:'SÌ', no:'NO', answer:'Risposta', learn:'Perché', next:'Turno successivo', respond:'Rispondi alla domanda', pass:'Passa il dispositivo al giocatore che deve rispondere.', computerAsks:'Il computer domanda:', inconsistent:'Risposta non coerente con la carta segreta. Riprova.', wrongGuess:'Tentativo errato: la partita continua.', winner:'ha indovinato!', reveal:'La carta segreta era', newGame:'Nuova partita', search:'Cerca radionuclide o storia', all:'Tutti', medical:'Medicina', natural:'Naturali/NORM', cosmos:'Cosmogenici', fission:'Fissione/reattori', environment:'Ambiente', industry:'Industria', halfLife:'Tempo di dimezzamento', mass:'Numero di massa', neutrons:'Neutroni', didYouKnow:'Lo sapevi che…', sourceStatus:'Stato editoriale', original:'Mazzo originale', expanded:'Espansione candidata', questionUnknown:'Non ho ancora interpretato questa domanda. Riformula o usa una domanda suggerita.', questionUnsupported:'Domanda sensata, ma richiede dati non ancora validati.', questionInvalid:'La domanda deve ammettere risposta SÌ o NO.', credits:'Versione digitale ispirata al gioco depositato su INFN Open Access Repository.', dataNote:'Prototipo web pulito: le carte di espansione e i dati avanzati devono essere validati fonte per fonte prima della pubblicazione.' },
  en: { title:'Guess the Radionuclide', subtitle:"A radioactive game for tomorrow's physicists!", play:'Play', atlas:'Atlas', about:'Credits & sources', setup:'Set up match', mode:'Mode', soloEasy:'Solo · learning', soloHard:'Solo · challenge', local:'Two players · one device', level:'Level', explorer:'Explorer', curious:'Curious', scientist:'Scientist', expert:'Expert', assistance:'Elimination', assisted:'Automatic', manual:'Manual', deck:'Deck', full:'All', start:'Start', pickSolo:'Choose your secret card', pick1:'Player 1, choose your secret card', pick2:'Pass the device. Player 2, choose a secret card', hide:'Do not show the card to your opponent.', turn:'Turn', player:'Player', computer:'Computer', secret:'Your card', ask:'Ask a YES/NO question', placeholder:'E.g. Could I find it in lettuce grown at Fukushima?', submit:'Ask', guess:'Guess', quick:'Suggested questions', candidates:'possible cards', yes:'YES', no:'NO', answer:'Answer', learn:'Why', next:'Next turn', respond:'Answer the question', pass:'Pass the device to the player who must answer.', computerAsks:'Computer asks:', inconsistent:'Answer does not match the secret card. Try again.', wrongGuess:'Wrong guess: the match continues.', winner:'guessed correctly!', reveal:'The secret card was', newGame:'New match', search:'Search radionuclide or story', all:'All', medical:'Medicine', natural:'Natural/NORM', cosmos:'Cosmogenic', fission:'Fission/reactors', environment:'Environment', industry:'Industry', halfLife:'Half-life', mass:'Mass number', neutrons:'Neutrons', didYouKnow:'Did you know…', sourceStatus:'Editorial status', original:'Original deck', expanded:'Candidate expansion', questionUnknown:'I cannot interpret this question yet. Rephrase or use a suggestion.', questionUnsupported:'Meaningful question, but it requires data not yet validated.', questionInvalid:'The question must be answerable with YES or NO.', credits:'Digital version inspired by the game deposited in the INFN Open Access Repository.', dataNote:'Clean web prototype: expansion cards and advanced data must be source-validated before publication.' },
  fr: { title:'Devine le radionucléide', subtitle:'Un jeu radioactif pour les physiciens du futur !', play:'Jouer', atlas:'Atlas', about:'Crédits et sources', setup:'Configurer la partie', mode:'Mode', soloEasy:'Solo · pédagogique', soloHard:'Solo · défi', local:'Deux joueurs · un appareil', level:'Niveau', explorer:'Explorateur', curious:'Curieux', scientist:'Scientifique', expert:'Expert', assistance:'Élimination', assisted:'Automatique', manual:'Manuelle', deck:'Paquet', full:'Toutes', start:'Commencer', pickSolo:'Choisissez votre carte secrète', pick1:'Joueur 1, choisissez la carte secrète', pick2:'Passez l’appareil. Joueur 2, choisissez une carte secrète', hide:'Ne montrez pas la carte à l’adversaire.', turn:'Tour', player:'Joueur', computer:'Ordinateur', secret:'Votre carte', ask:'Posez une question OUI/NON', placeholder:'Ex. Peut-on le trouver dans une salade cultivée à Fukushima ?', submit:'Poser', guess:'Proposer', quick:'Questions suggérées', candidates:'cartes possibles', yes:'OUI', no:'NON', answer:'Réponse', learn:'Pourquoi', next:'Tour suivant', respond:'Répondez à la question', pass:'Passez l’appareil au joueur qui doit répondre.', computerAsks:'L’ordinateur demande :', inconsistent:'Réponse non cohérente avec la carte secrète. Réessayez.', wrongGuess:'Mauvaise proposition : la partie continue.', winner:'a trouvé !', reveal:'La carte secrète était', newGame:'Nouvelle partie', search:'Chercher radionucléide ou histoire', all:'Tous', medical:'Médecine', natural:'Naturels/NORM', cosmos:'Cosmogéniques', fission:'Fission/réacteurs', environment:'Environnement', industry:'Industrie', halfLife:'Période radioactive', mass:'Nombre de masse', neutrons:'Neutrons', didYouKnow:'Le saviez-vous ?', sourceStatus:'Statut éditorial', original:'Paquet original', expanded:'Extension candidate', questionUnknown:'Je ne comprends pas encore cette question. Reformulez ou utilisez une suggestion.', questionUnsupported:'Question pertinente, mais elle exige des données non encore validées.', questionInvalid:'La question doit admettre une réponse OUI ou NON.', credits:'Version numérique inspirée du jeu déposé dans l’INFN Open Access Repository.', dataNote:'Prototype web propre : les cartes d’extension et données avancées devront être validées source par source avant publication.' }
};

const MODE = { alpha:'α', 'beta-':'β⁻', 'beta+':'β⁺', ec:'ε', gamma:'γ', it:'IT', sf:'sf' };
const COLOR = { alpha:'#fde006', 'beta-':'#63b5c1', 'beta+':'#ff744f', ec:'#ff744f', gamma:'#ff744f', it:'#f8fafc', sf:'#e2e8f0' };
function card(id, names, Z, A, seconds, modes, tags, original, story) { return { id, name:{it:names[0], en:names[1]||names[0], fr:names[2]||names[0]}, Z, A, seconds, modes, tags, original, story:{it:story, en:story, fr:story} }; }

const CARDS = [
card('Tb-149',['Terbio-149','Terbium-149','Terbium-149'],65,149,14760,['alpha','beta+','gamma'],['medical','therapy'],true,'Candidato teranostico raro che combina emissione alfa e possibilità di imaging.'),
card('At-211',['Astato-211','Astatine-211','Astate-211'],85,211,25970,['alpha','ec','gamma'],['medical','therapy'],true,'È studiato per terapie alfa mirate, con un raggio d’azione molto corto.'),
card('O-15',['Ossigeno-15','Oxygen-15','Oxygène-15'],8,15,122.2,['beta+'],['medical','pet'],true,'In PET può seguire processi legati all’ossigeno e al flusso sanguigno.'),
card('N-13',['Azoto-13','Nitrogen-13','Azote-13'],7,13,597.9,['beta+'],['medical','pet'],true,'È un emettitore di positroni impiegato in traccianti PET a vita breve.'),
card('F-18',['Fluoro-18','Fluorine-18','Fluor-18'],9,18,6586,['beta+'],['medical','pet','diagnosis'],true,'È il radionuclide della FDG-PET, uno degli esami più noti della diagnostica nucleare.'),
card('I-123',['Iodio-123','Iodine-123','Iode-123'],53,123,47570,['ec','gamma'],['medical','diagnosis','thyroid','spect'],true,'Poiché lo iodio viene captato dalla tiroide, è utile per imaging diagnostico.'),
card('I-125',['Iodio-125','Iodine-125','Iode-125'],53,125,5132765,['ec','gamma'],['medical','brachytherapy'],true,'È stato impiegato in sorgenti sigillate e brachiterapia.'),
card('C-14',['Carbonio-14','Carbon-14','Carbone-14'],6,14,1.808e11,['beta-'],['natural','cosmogenic','dating','environment'],true,'È prodotto naturalmente dai raggi cosmici in atmosfera ed è l’orologio della datazione radiocarbonica.'),
card('H-3',['Trizio','Tritium','Tritium'],1,3,3.889e8,['beta-'],['natural','cosmogenic','environment','fusion'],true,'È un isotopo dell’idrogeno: tracciante ambientale e candidato combustibile per la fusione.'),
card('I-131',['Iodio-131','Iodine-131','Iode-131'],53,131,693100,['beta-','gamma'],['medical','therapy','fission','fallout','food','thyroid'],true,'Può trattare patologie tiroidee ed è anche rilevante nei rilasci di prodotti di fissione.'),
card('Co-60',['Cobalto-60','Cobalt-60','Cobalt-60'],27,60,1.663e8,['beta-','gamma'],['medical','industry','sterilisation'],true,'Le sue emissioni gamma sono associate a radioterapia storica, sterilizzazione e radiografia industriale.'),
card('Tb-161',['Terbio-161','Terbium-161','Terbium-161'],65,161,595296,['beta-','gamma'],['medical','therapy'],true,'È studiato come radionuclide terapeutico per piccole lesioni.'),
card('Cs-137',['Cesio-137','Caesium-137','Césium-137'],55,137,9.49e8,['beta-','gamma'],['fission','fallout','food','environment'],true,'È tra i radionuclidi a lunga vita più associati a fallout e catena alimentare.'),
card('Y-90',['Ittrio-90','Yttrium-90','Yttrium-90'],39,90,230400,['beta-'],['medical','therapy','fission'],true,'È un emettitore beta usato in terapie radionuclidiche.'),
card('Sr-89',['Stronzio-89','Strontium-89','Strontium-89'],38,89,4360000,['beta-'],['medical','therapy','fission','bone'],true,'La chimica simile al calcio lo rende interessante per applicazioni ossee.'),
card('Lu-177',['Lutezio-177','Lutetium-177','Lutécium-177'],71,177,574387,['beta-','gamma'],['medical','therapy','theranostic'],true,'È centrale in diverse terapie radioligandiche, associando terapia e imaging.'),
card('Ir-192',['Iridio-192','Iridium-192','Iridium-192'],77,192,6380000,['beta-','gamma'],['medical','brachytherapy','industry'],true,'È utilizzato in brachiterapia e controlli radiografici industriali.'),
card('Kr-85',['Kripton-85','Krypton-85','Krypton-85'],36,85,3.389e8,['beta-','gamma'],['fission','environment','noble-gas'],true,'Gas nobile di fissione, può tracciare attività del ciclo del combustibile.'),
card('Be-7',['Berillio-7','Beryllium-7','Béryllium-7'],4,7,4598200,['ec','gamma'],['natural','cosmogenic','environment'],true,'È prodotto dai raggi cosmici nell’atmosfera e aiuta a studiare la deposizione atmosferica.'),
card('U-235',['Uranio-235','Uranium-235','Uranium-235'],92,235,2.221e16,['alpha','sf','gamma'],['natural','norm','fuel','fission'],true,'È naturale e fissile: protagonista della storia dell’energia nucleare.'),
card('U-238',['Uranio-238','Uranium-238','Uranium-238'],92,238,1.410e17,['alpha','sf','gamma'],['natural','norm','fuel','radon'],true,'È il principale isotopo dell’uranio naturale e capostipite della catena del radon-222.'),
card('Rn-222',['Radon-222','Radon-222','Radon-222'],86,222,330350,['alpha','gamma'],['natural','norm','radon','environment'],true,'Gas radioattivo naturale, può accumularsi negli ambienti chiusi.'),
card('Ra-226',['Radio-226','Radium-226','Radium-226'],88,226,5.049e10,['alpha','gamma'],['natural','norm','radon','history'],true,'È il genitore del radon-222 ed è legato alla storia delle pitture luminescenti.'),
card('Th-232',['Torio-232','Thorium-232','Thorium-232'],90,232,4.434e17,['alpha','gamma'],['natural','norm'],true,'Capostipite di una catena naturale, è presente in minerali e materiali terrestri.'),
card('K-40',['Potassio-40','Potassium-40','Potassium-40'],19,40,3.938e16,['beta-','ec','gamma','beta+'],['natural','norm','food','dating'],true,'È naturalmente presente nel potassio: anche il corpo umano ne contiene una piccola attività.'),
card('Tc-99m',['Tecnezio-99m','Technetium-99m','Technétium-99m'],43,99,21624,['it','gamma'],['medical','diagnosis','spect','generator'],true,'Figlio del molibdeno-99, è un protagonista dell’imaging diagnostico SPECT.'),
card('Ga-68',['Gallio-68','Gallium-68','Gallium-68'],31,68,4076,['beta+'],['medical','pet','generator'],false,'Può essere ottenuto da un generatore e usato in PET.'),
card('Cu-64',['Rame-64','Copper-64','Cuivre-64'],29,64,45720,['beta+','beta-','ec'],['medical','pet','theranostic'],false,'Il suo decadimento versatile è interessante per diagnostica e teranostica.'),
card('Zr-89',['Zirconio-89','Zirconium-89','Zirconium-89'],40,89,282240,['beta+'],['medical','pet','antibody'],false,'La sua durata è compatibile con studi PET di alcune biomolecole lente.'),
card('Ac-225',['Attinio-225','Actinium-225','Actinium-225'],89,225,857000,['alpha'],['medical','therapy'],false,'È tra i radionuclidi emergenti nella terapia alfa mirata.'),
card('Ra-223',['Radio-223','Radium-223','Radium-223'],88,223,987000,['alpha'],['medical','therapy','bone'],false,'La chimica affine al calcio lo associa a terapie in ambito osseo.'),
card('Sr-90',['Stronzio-90','Strontium-90','Strontium-90'],38,90,9.08e8,['beta-'],['fission','fallout','food','bone'],false,'Prodotto di fissione a lunga vita, segue chimicamente il calcio.'),
card('Cs-134',['Cesio-134','Caesium-134','Césium-134'],55,134,6.51e7,['beta-','gamma'],['fission','fallout','food','environment'],false,'Con il Cs-137 può contribuire a caratterizzare contaminazioni da reattore.'),
card('Am-241',['Americio-241','Americium-241','Américium-241'],95,241,1.365e10,['alpha','gamma'],['waste','industry','smoke'],false,'È noto per l’impiego in alcuni rivelatori di fumo a ionizzazione.'),
card('Pu-238',['Plutonio-238','Plutonium-238','Plutonium-238'],94,238,2.77e9,['alpha'],['space','energy','rtg'],false,'Il calore del suo decadimento ha alimentato generatori radioisotopici per missioni spaziali.'),
card('Al-26',['Alluminio-26','Aluminium-26','Aluminium-26'],13,26,2.26e13,['beta+','gamma'],['stellar','space','meteorite'],false,'La sua emissione gamma racconta nucleosintesi recente nella Galassia.'),
card('Fe-60',['Ferro-60','Iron-60','Fer-60'],26,60,8.27e13,['beta-','gamma'],['stellar','supernova'],false,'Può lasciare tracce di supernove avvenute vicino alla Terra.'),
card('Pb-210',['Piombo-210','Lead-210','Plomb-210'],82,210,7.04e8,['beta-','gamma'],['natural','radon','environment','dating'],false,'Discendente del radon, è impiegato nello studio di sedimenti e deposizioni recenti.'),
card('Po-210',['Polonio-210','Polonium-210','Polonium-210'],84,210,1.196e7,['alpha'],['natural','food','history'],false,'Emettitore alfa della catena naturale dell’uranio, con una storia nota anche fuori dai laboratori.'),
card('Rb-87',['Rubidio-87','Rubidium-87','Rubidium-87'],37,87,1.54e18,['beta-'],['natural','dating','geology'],false,'Il sistema rubidio-stronzio è un orologio per ricostruire la storia delle rocce.')
];

function normalise(v){ return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,"'"); }
function has(c,t){ return c.tags.includes(t); }
function fmt(seconds, lang){ const units=lang==='it'?[[31557600,'a'],[86400,'g'],[3600,'h'],[60,'min'],[1,'s']]:lang==='fr'?[[31557600,'a'],[86400,'j'],[3600,'h'],[60,'min'],[1,'s']]:[[31557600,'y'],[86400,'d'],[3600,'h'],[60,'min'],[1,'s']]; const u=units.find(([f])=>seconds>=f)||units.at(-1); const val=seconds/u[0]; return `${val.toLocaleString(lang,{maximumFractionDigits:val>=100?0:val>=10?1:2})} ${u[1]}`; }
function mainColor(c){ return COLOR[['alpha','beta-','beta+','it','ec'].find(m=>c.modes.includes(m))] || '#f8fafc'; }
function ok(yes, concept, explanation){ return {type:'ok', yes:Boolean(yes), concept, explanation}; }
function interpret(c, input, lang='it'){
 const q=normalise(input.trim()); if(!q) return {type:'invalid'};
 const neg=/\b(non|not|isn\'?t|doesn\'?t|cant|can\'?t|ne |pas |jamais|aucun|nessun)\b/.test(q);
 const wrap=(r)=> neg ? {...r, yes:!r.yes, explanation:r.explanation+' (Domanda interpretata in forma negativa.)'} : r;
 if(/^(come|what|quale|quel|comment|pourquoi|perche)( |$)/.test(q)&&!/(si usa|used|utilis|decad|emett|emivita|half|periode)/.test(q)) return {type:'invalid'};
 if(/(gialla|yellow|jaune)/.test(q)) return wrap(ok(c.modes.includes('alpha'),'α','Il giallo identifica il decadimento alfa.'));
 if(/(azzurra|blu|blue|bleu)/.test(q)) return wrap(ok(c.modes.includes('beta-'),'β⁻','L’azzurro identifica il decadimento beta meno.'));
 if(/(rossa|arancione|red|orange|rouge)/.test(q)) return wrap(ok(c.modes.includes('beta+')||c.modes.includes('ec'),'β⁺/ε','L’arancio identifica emissione β⁺ o cattura elettronica.'));
 if(/(beta[ ]*meno|beta[ ]*-|β[ ]*-|bêta[ ]*moins|antineutrin)/.test(q)) return wrap(ok(c.modes.includes('beta-'),'β⁻','Nel β⁻ viene emesso un elettrone e un antineutrino elettronico.'));
 if(/(beta[ ]*piu|beta[ ]*[+]|β[ ]*[+]|positron|positrone|bêta[ ]*plus)/.test(q)) return wrap(ok(c.modes.includes('beta+'),'β⁺','L’emissione β⁺ è alla base della PET.'));
 if(/(cattura elettronica|electron capture|capture electronique|capture électronique|epsilon|ε)/.test(q)) return wrap(ok(c.modes.includes('ec'),'ε','Nella cattura elettronica un protone cattura un elettrone.'));
 if(/(transizione isomerica|metastabil|isomeric|isomerique|isomérique)/.test(q)) return wrap(ok(c.modes.includes('it'),'IT','Uno stato metastabile può diseccitarsi per transizione isomerica.'));
 if(/(alfa|alpha|α)/.test(q)) return wrap(ok(c.modes.includes('alpha'),'α','Nel decadimento alfa A diminuisce di 4 e Z di 2.'));
 if(/(gamma|γ)/.test(q)&&!/(energia|energy|energie|énergie|kev|mev)/.test(q)) return wrap(ok(c.modes.includes('gamma')||c.modes.includes('it'),'γ','Un fotone gamma non cambia A o Z.'));
 let m=q.match(/(?:massa|mass|masse|numero).*?(?:maggiore|superior|greater|plus grand|piu grande|>)[ ]*(?:di|than|que)?[ ]*([0-9]+)/); if(m) return ok(c.A>Number(m[1]),'A',`Il numero di massa è A = ${c.A}.`);
 m=q.match(/(?:massa|mass|masse|numero).*?(?:minore|inferior|less|plus petit|piu piccolo|<)[ ]*(?:di|than|que)?[ ]*([0-9]+)/); if(m) return ok(c.A<Number(m[1]),'A',`Il numero di massa è A = ${c.A}.`);
 m=q.match(/(?:neutroni|neutrons).*?(?:maggiore|greater|plus grand|>)[ ]*(?:di|than|que)?[ ]*([0-9]+)/); if(m) return ok(c.A-c.Z>Number(m[1]),'N',`Il numero di neutroni è N = ${c.A-c.Z}.`);
 if(/(?:neutroni|neutrons).*?(?:pari|even|pair)/.test(q)) return ok((c.A-c.Z)%2===0,'N',`Il numero di neutroni è N = ${c.A-c.Z}.`);
 m=q.match(/(?:emivita|tempo di dimezzamento|dimezzamento|half.?life|periode|période).*?(piu lunga|piu lungo|maggiore|superiore|greater|longer|plus long|>|piu breve|piu corto|minore|inferiore|less|shorter|plus court|<)[ ]*(?:di|than|que)?[ ]*([0-9]+(?:[.,][0-9]+)?)[ ]*(second|sec|minut|min|or[ae]?|hour|heure|h|giorn|day|jour|settiman|week|semain|mes[ei]?|month|mois|ann|year|ans)/);
 if(m){ const comp=m[1], number=Number(m[2].replace(',','.')), unit=m[3]; const f=/second|sec/.test(unit)?1:/min/.test(unit)?60:/or|hour|heure|^h$/.test(unit)?3600:/gior|day|jour/.test(unit)?86400:/settiman|week|semain/.test(unit)?604800:/mes|month|mois/.test(unit)?2629800:31557600; const gt=/(lunga|lungo|maggiore|superiore|greater|longer|plus long|>)/.test(comp); return ok(gt?c.seconds>number*f:c.seconds<number*f,'T½',`${c.name[lang]} ha T½ = ${fmt(c.seconds,lang)}.`); }
 const rules=[[/naturale|natural|naturel|in natura|dans la nature/, has(c,'natural')||has(c,'norm')||has(c,'cosmogenic'),'origine naturale','Naturali: primordiali, catene naturali o cosmogenici.'],[/cosmogen|raggi cosmici|cosmic|rayons cosmiques|atmosfer/, has(c,'cosmogenic'),'origine cosmogenica','I cosmogenici sono prodotti da interazioni dei raggi cosmici.'],[/norm|minerali|raw material|matiere premiere|matière première/, has(c,'norm'),'NORM','I NORM sono radionuclidi naturali in materiali terrestri.'],[/pet|positron emission/, has(c,'pet'),'PET','La PET usa emettitori di positroni.'],[/spect|scintigraf/, has(c,'spect'),'SPECT','La SPECT rileva fotoni gamma.'],[/medicina|ospedale|hospital|hopital|hôpital|patient|paziente/, has(c,'medical'),'medicina nucleare','In medicina nucleare si scelgono nuclidi per diagnosi o terapia.'],[/cura|curare|terapia|therapy|traitement|therapie|thérapie|tumor|tumour|canc/, has(c,'therapy'),'terapia','La terapia radionuclidica deposita dose nel bersaglio.'],[/fissione|fission|reattore|reactor|reacteur|réacteur|centrale/, has(c,'fission')||has(c,'reactor')||has(c,'fuel'),'fissione/reattori','Fissione e irraggiamento producono radionuclidi rilevanti.'],[/chernobyl|cernobyl|tchernobyl|fukushima|fallout|insalat|lattug|lettuce|salade|verdura|vegetal|végétal|food|cibo|latte|milk|lait|funghi|mushroom|champignon/, has(c,'fallout')||has(c,'food'),'fallout e alimenti','I-131, Cs-134, Cs-137 e Sr-90 possono essere rilevanti dopo rilasci.'],[/radon|aria interna|indoor|air interieur|air intérieur/, has(c,'radon'),'radon','Rn-222 e discendenti sono importanti per esposizione indoor.'],[/datazione|dating|datation|reperto|archeolog|roccia|rock|roche/, has(c,'dating'),'datazione','Alcuni decadimenti funzionano da orologi naturali.'],[/stella|stellar|etoile|étoile|supernova|galassi|galaxy|nucleosintesi|nucleosynthesis/, has(c,'stellar')||has(c,'supernova'),'nucleosintesi','Al-26 e Fe-60 raccontano nucleosintesi e supernove.'],[/spazio|space|espace|sonda|probe|missione spaziale|mars|marte/, has(c,'space')||has(c,'rtg'),'spazio','Alcuni radioisotopi alimentano generatori spaziali.'],[/fumo|smoke|fumee|fumée|incendio|detector/, has(c,'smoke'),'rivelatori di fumo','Am-241 è noto per rivelatori a ionizzazione.'],[/industr|radiografi|non distruttiv|weld|saldatur/, has(c,'industry'),'industria','Sorgenti gamma possono servire per controlli non distruttivi.']];
 for (const [re,yes,concept,exp] of rules) if(re.test(q)) return wrap(ok(yes,concept,exp));
 if(/energia.*gamma|gamma.*energia|kev|mev|spin|parita|parità|parity/.test(q)) return {type:'unsupported'};
 return {type:'unknown'};
}
const SUGGESTIONS={explorer:['La carta è gialla?','La carta è azzurra?','Il numero di massa è maggiore di 100?','Si usa in ospedale?'], curious:['È naturale?','È cosmogenico?','Può trovarsi in un’insalata coltivata a Fukushima?','Si usa in terapia?','Può servire per datare qualcosa?'], scientist:['Decade beta meno?','Emette positroni?','Il tempo di dimezzamento è più lungo di 1 anno?','È un prodotto di fissione?','È usato in PET?'], expert:['Emette un antineutrino?','Ha transizione isomerica?','Il numero di neutroni è pari?','È un NORM?','Ha un ruolo nella nucleosintesi stellare?']};
const AI_QUESTIONS=['È naturale?','È usato in medicina?','Decade alfa?','Decade beta meno?','È cosmogenico?','È un prodotto di fissione?','Il tempo di dimezzamento è più lungo di 1 anno?','È usato in terapia?','Può servire per datare qualcosa?','È legato al radon?','Ha un ruolo nella nucleosintesi stellare?'];
function chooseDeck(size){ if(size>=CARDS.length) return CARDS; const tags=['medical','natural','fission','cosmogenic','therapy','environment','stellar','space','waste']; const chosen=[]; tags.forEach(t=>{const c=CARDS.find(x=>x.tags.includes(t)&&!chosen.includes(x)); if(c&&chosen.length<size) chosen.push(c);}); [...CARDS.filter(c=>c.original),...CARDS.filter(c=>!c.original)].forEach(c=>{if(chosen.length<size&&!chosen.includes(c)) chosen.push(c)}); return chosen; }
function split(cards,q){ return cards.reduce((a,c)=>{const e=interpret(c,q); if(e.type==='ok') a[e.yes?0:1]++; return a;},[0,0]); }
function computerQuestion(candidates,easy){ const usable=AI_QUESTIONS.filter(q=>{const [y,n]=split(candidates,q); return y>0&&n>0}); if(!usable.length) return null; if(easy) return usable[Math.floor(Math.random()*usable.length)]; return usable.sort((a,b)=>Math.abs(split(candidates,a)[0]-split(candidates,a)[1])-Math.abs(split(candidates,b)[0]-split(candidates,b)[1]))[0]; }
function Logo({compact=false}){return <div className={(compact?'logo small':'logo')}><span>Indovina il</span><br/><b>Radio</b><i>Nuclide</i></div>}
function Pill({active,onClick,children}){return <button onClick={onClick} className={active?'pill active':'pill'}>{children}</button>}
function NuclideCard({item,lang,inactive=false,onClick,compact=false}){return <button onClick={onClick} className={(compact?'card compact':'card')+(inactive?' inactive':'')}><div className="stripe" style={{background:mainColor(item)}}/><h3>{item.name[lang]}</h3><p className="half">{fmt(item.seconds,lang)}</p><div className="modes">{item.modes.map(m=><span key={m} style={{background:COLOR[m]||'white'}}>{MODE[m]}</span>)}</div>{!compact&&<p className="story">{item.story[lang]}</p>}</button>}
function Modal({children,close}){return <div className="modalBg" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}>{children}</div></div>}
function Section({title,children}){return <section className="setupSection"><h2>{title}</h2><div className="row">{children}</div></section>}
function App(){
 const [lang,setLang]=useState('it'), t=TEXT[lang]; const [screen,setScreen]=useState('home'); const [config,setConfig]=useState({mode:'soloEasy',level:'curious',assist:'assisted',deckSize:26}); const [deck,setDeck]=useState([]), [pickStep,setPickStep]=useState(1), [p1,setP1]=useState(null), [p2,setP2]=useState(null); const [current,setCurrent]=useState(1), [phase,setPhase]=useState('ask'), [question,setQuestion]=useState(''), [pending,setPending]=useState(null), [remaining,setRemaining]=useState({1:[],2:[]}), [down,setDown]=useState({1:[],2:[]}), [computerRem,setComputerRem]=useState([]), [log,setLog]=useState([]), [msg,setMsg]=useState(''), [winner,setWinner]=useState(null), [guess,setGuess]=useState(false), [detail,setDetail]=useState(null), [search,setSearch]=useState(''), [filter,setFilter]=useState('all');
 const addLog=e=>setLog(l=>[e,...l].slice(0,8)); const start=()=>{const d=chooseDeck(config.deckSize); setDeck(d); setP1(null); setP2(null); setCurrent(1); setPhase('ask'); setPending(null); setMsg(''); setWinner(null); setGuess(false); setLog([]); setRemaining({1:d.map(c=>c.id),2:d.map(c=>c.id)}); setDown({1:[],2:[]}); setComputerRem(d.map(c=>c.id)); setPickStep(1); setScreen('pick')};
 const chooseSecret=c=>{ if(pickStep===1){setP1(c); if(config.mode.startsWith('solo')){const opt=deck.filter(x=>x.id!==c.id); setP2(opt[Math.floor(Math.random()*opt.length)]); setScreen('game')} else setPickStep(2)} else {setP2(c); setScreen('game')}};
 const active=config.mode.startsWith('solo')?1:current; const own=config.mode.startsWith('solo')?p1:(current===1?p1:p2); const visible=player=>deck.filter(c=>remaining[player].includes(c.id)&&!down[player].includes(c.id)); const filterCards=(player,q,ans)=>{if(config.assist!=='assisted') return; setRemaining(prev=>({...prev,[player]:prev[player].filter(id=>{const e=interpret(deck.find(c=>c.id===id),q,lang); return e.type!=='ok'||e.yes===ans})}))};
 const startComputer=()=>{const cand=deck.filter(c=>computerRem.includes(c.id)); if(cand.length<=1){const sel=cand[0]||deck[0]; setPending({kind:'computerGuess', q:`${lang==='it'?'Il tuo radionuclide è':lang==='fr'?'Votre radionucléide est':'Is your radionuclide'} ${sel.name[lang]}?`, item:sel}); setPhase('computerAnswer'); return;} const q=computerQuestion(cand,config.mode==='soloEasy'); setPending(q?{kind:'computerQuestion',q}:{kind:'computerGuess',q:`${lang==='it'?'Il tuo radionuclide è':lang==='fr'?'Votre radionucléide est':'Is your radionuclide'} ${cand[0].name[lang]}?`,item:cand[0]}); setPhase('computerAnswer')};
 const submit=(value=question)=>{const q=value.trim(); const target=config.mode.startsWith('solo')?p2:(current===1?p2:p1); const e=interpret(target,q,lang); if(e.type!=='ok'){setMsg(e.type==='invalid'?t.questionInvalid:e.type==='unsupported'?t.questionUnsupported:t.questionUnknown); return;} setMsg(''); setQuestion(''); if(config.mode.startsWith('solo')){filterCards(1,q,e.yes); addLog({who:1,q,answer:e.yes,explanation:e.explanation}); setPending({kind:'shownAnswer',q,answer:e.yes,explanation:e.explanation,next:'computer'}); setPhase('showAnswer')} else {setPending({kind:'localQuestion',q,e}); setPhase('localAnswer')}};
 const respondLocal=ans=>{const target=current===1?p2:p1; const exp=interpret(target,pending.q,lang); if(exp.yes!==ans){setMsg(t.inconsistent); return;} setMsg(''); filterCards(current,pending.q,ans); addLog({who:current,q:pending.q,answer:ans,explanation:exp.explanation}); setPending({kind:'shownAnswer',q:pending.q,answer:ans,explanation:exp.explanation,next:'switch'}); setPhase('showAnswer')};
 const next=()=>{const n=pending?.next; setPending(null); setMsg(''); if(n==='computer') startComputer(); else {setCurrent(p=>p===1?2:1); setPhase('ask')}};
 const respondComputer=ans=>{if(pending.kind==='computerGuess'){const exp=pending.item.id===p1.id; if(ans!==exp){setMsg(t.inconsistent); return;} addLog({who:'AI',q:pending.q,answer:ans}); if(exp){setWinner('AI'); setPhase('end')} else {setComputerRem(prev=>prev.filter(id=>id!==pending.item.id)); setPending(null); setPhase('ask')} return;} const e=interpret(p1,pending.q,lang); if(ans!==e.yes){setMsg(t.inconsistent); return;} setMsg(''); setComputerRem(prev=>prev.filter(id=>interpret(deck.find(c=>c.id===id),pending.q,lang).yes===ans)); addLog({who:'AI',q:pending.q,answer:ans,explanation:e.explanation}); setPending(null); setPhase('ask')};
 const attempt=c=>{const target=config.mode.startsWith('solo')?p2:(current===1?p2:p1); const correct=c.id===target.id; addLog({who:current,q:`${t.guess}: ${c.name[lang]}`,answer:correct}); setGuess(false); if(correct){setWinner(current); setPhase('end'); return;} setMsg(t.wrongGuess); if(config.mode.startsWith('solo')) startComputer(); else setCurrent(p=>p===1?2:1)};
 const toggle=id=>{if(config.assist==='manual'&&phase==='showAnswer') setDown(prev=>({...prev,[active]:prev[active].includes(id)?prev[active].filter(x=>x!==id):[...prev[active],id]}))};
 const catalogue=useMemo(()=>CARDS.filter(c=>{const q=normalise(search); return (!q||normalise(`${c.id} ${c.name[lang]} ${c.story[lang]}`).includes(q))&&(filter==='all'||c.tags.includes(filter))}),[search,filter,lang]);
 return <div><header><button onClick={()=>setScreen('home')} className="brand"><Atom/> <span>{t.title}</span></button><div className="langs"><Globe2/>{['it','en','fr'].map(l=><button key={l} onClick={()=>setLang(l)} className={lang===l?'sel':''}>{l}</button>)}</div></header>
 {screen==='home'&&<main className="hero"><section><Logo/><p>{t.subtitle}</p><p>{CARDS.length} radionuclidi, gioco multilingue, domande narrative e fisiche.</p><div className="actions"><button onClick={()=>setScreen('setup')}><Play/> {t.play}</button><button onClick={()=>setScreen('atlas')}><BookOpen/> {t.atlas}</button><button onClick={()=>setScreen('about')}><Info/> {t.about}</button></div><small>{t.credits} <a href={DOI}>DOI</a></small></section><div className="grid cards9">{chooseDeck(9).map(c=><NuclideCard key={c.id} item={c} lang={lang} compact />)}</div></main>}
 {screen==='setup'&&<main className="narrow"><h1>{t.setup}</h1><Section title={t.mode}>{[['soloEasy',t.soloEasy],['soloHard',t.soloHard],['local',t.local]].map(([v,l])=><Pill key={v} active={config.mode===v} onClick={()=>setConfig({...config,mode:v})}>{l}</Pill>)}</Section><Section title={t.level}>{[['explorer',t.explorer],['curious',t.curious],['scientist',t.scientist],['expert',t.expert]].map(([v,l])=><Pill key={v} active={config.level===v} onClick={()=>setConfig({...config,level:v})}>{l}</Pill>)}</Section><Section title={t.assistance}>{[['assisted',t.assisted],['manual',t.manual]].map(([v,l])=><Pill key={v} active={config.assist===v} onClick={()=>setConfig({...config,assist:v})}>{l}</Pill>)}</Section><Section title={t.deck}>{[12,18,26,CARDS.length].map(n=><Pill key={n} active={config.deckSize===n} onClick={()=>setConfig({...config,deckSize:n})}>{n===CARDS.length?t.full:n}</Pill>)}</Section><button className="primary" onClick={start}>{t.start}</button></main>}
 {screen==='pick'&&<main><h1>{config.mode.startsWith('solo')?t.pickSolo:pickStep===1?t.pick1:t.pick2}</h1>{pickStep===2&&<p className="warn">{t.hide}</p>}<div className="grid">{deck.map(c=><NuclideCard key={c.id} item={c} lang={lang} compact onClick={()=>chooseSecret(c)}/>)}</div></main>}
 {screen==='game'&&<main>{phase==='end'?<End t={t} lang={lang} winner={winner} p1={p1} p2={p2} detail={setDetail} restart={()=>setScreen('setup')}/>:<><div className="gameTop"><h1>{t.turn}: {config.mode.startsWith('solo')?(phase==='computerAnswer'?t.computer:t.player):`${t.player} ${current}`}</h1><span>{visible(active).length} {t.candidates}</span></div><div className="game"><aside>{own&&<div className="secret"><b>{t.secret}:</b> {own.name[lang]} <button onClick={()=>setDetail(own)}><Info/> </button></div>}{phase==='ask'&&<><h2>{t.ask}</h2><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder={t.placeholder}/><button className="primary" onClick={()=>submit()}>{t.submit}</button><button onClick={()=>setGuess(true)}>{t.guess}</button><h3>{t.quick}</h3><div className="suggestions">{SUGGESTIONS[config.level].map(q=><button key={q} onClick={()=>submit(q)}>{q}</button>)}</div></>}{phase==='showAnswer'&&<><div className={pending.answer?'answer yes':'answer no'}><small>{t.answer}</small><strong>{pending.answer?t.yes:t.no}</strong><p>{pending.q}</p></div><p className="explain"><b>{t.learn}:</b> {pending.explanation}</p><button className="primary" onClick={next}>{t.next}</button></>}{phase==='localAnswer'&&<><h2>{t.respond}</h2><p>{t.pass}</p><p className="questionBox">{pending.q}</p><button className="yesBtn" onClick={()=>respondLocal(true)}>{t.yes}</button><button className="noBtn" onClick={()=>respondLocal(false)}>{t.no}</button></>}{phase==='computerAnswer'&&<><h2>{t.computerAsks}</h2><p className="questionBox">{pending.q}</p><button className="yesBtn" onClick={()=>respondComputer(true)}>{t.yes}</button><button className="noBtn" onClick={()=>respondComputer(false)}>{t.no}</button></>}{msg&&<p className="warn">{msg}</p>}{log.length>0&&<div className="log"><h3>Log</h3>{log.slice(0,4).map((e,i)=><p key={i}><b>{e.who==='AI'?t.computer:`${t.player} ${e.who}`}</b>: {e.q} <span className={e.answer?'green':'red'}>{e.answer?t.yes:t.no}</span></p>)}</div>}</aside><section className="grid board">{deck.map(c=><NuclideCard key={c.id} item={c} lang={lang} compact inactive={!remaining[active].includes(c.id)||down[active].includes(c.id)} onClick={()=>guess?attempt(c):toggle(c.id)}/>)}</section></div></>}</main>}
 {screen==='atlas'&&<main><div className="atlasTop"><h1>{t.atlas}</h1><div><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search}/></div></div><div className="row filters">{[['all',t.all],['medical',t.medical],['natural',t.natural],['cosmogenic',t.cosmos],['fission',t.fission],['environment',t.environment],['industry',t.industry]].map(([v,l])=><Pill key={v} active={filter===v} onClick={()=>setFilter(v)}>{l}</Pill>)}</div><div className="grid">{catalogue.map(c=><NuclideCard key={c.id} item={c} lang={lang} onClick={()=>setDetail(c)}/>)}</div></main>}
 {screen==='about'&&<main className="narrow"><Logo compact/><h1>{t.about}</h1><p>{t.credits}</p><p className="warn">{t.dataNote}</p><a href={DOI}>INFN Open Access Repository · DOI</a></main>}
 {detail&&<Modal close={()=>setDetail(null)}><button className="close" onClick={()=>setDetail(null)}><X/></button><h1>{detail.name[lang]}</h1><p><b>{t.halfLife}:</b> {fmt(detail.seconds,lang)}</p><div className="modes">{detail.modes.map(m=><span key={m} style={{background:COLOR[m]||'white'}}>{MODE[m]}</span>)}</div><div className="facts"><div>Z<br/><b>{detail.Z}</b></div><div>{t.mass}<br/><b>{detail.A}</b></div><div>{t.neutrons}<br/><b>{detail.A-detail.Z}</b></div></div><h2><Sparkles/> {t.didYouKnow}</h2><p>{detail.story[lang]}</p><p className="status"><b>{t.sourceStatus}:</b> {detail.original?t.original:t.expanded}</p></Modal>}
 </div>}
function End({t,lang,winner,p1,p2,detail,restart}){const label=winner==='AI'?t.computer:`${t.player} ${winner}`; const rev=winner==='AI'?p1:winner===1?p2:p1; return <div className="end"><Sparkles/><h1>{label} {t.winner}</h1><p>{t.reveal}</p><NuclideCard item={rev} lang={lang} onClick={()=>detail(rev)}/><button className="primary" onClick={restart}><RotateCcw/> {t.newGame}</button></div>}
createRoot(document.getElementById('root')).render(<App/>);
